config/routes.rb
# == Route Map
#
#                       Prefix Verb   URI Pattern                                                                              Controller#Action
#                  rails_admin        /admin                                                                                   RailsAdmin::Engine
#             new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#                 user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#         destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#            new_user_password GET    /users/password/new(.:format)                                                            users/passwords#new
#           edit_user_password GET    /users/password/edit(.:format)                                                           users/passwords#edit
#                user_password PATCH  /users/password(.:format)                                                                users/passwords#update
#                              PUT    /users/password(.:format)                                                                users/passwords#update
#                              POST   /users/password(.:format)                                                                users/passwords#create
#     cancel_user_registration GET    /users/cancel(.:format)                                                                  users/registrations#cancel
#        new_user_registration GET    /users/sign_up(.:format)                                                                 users/registrations#new
#       edit_user_registration GET    /users/edit(.:format)                                                                    users/registrations#edit
#            user_registration PATCH  /users(.:format)                                                                         users/registrations#update
#                              PUT    /users(.:format)                                                                         users/registrations#update
#                              DELETE /users(.:format)                                                                         users/registrations#destroy
#                              POST   /users(.:format)                                                                         users/registrations#create
#                      sign_in GET    /sign_in(.:format)                                                                       users/sessions#new
#                     sign_out GET    /sign_out(.:format)                                                                      users/sessions#destroy
#         users_user_icon_edit GET    /users/user_icon_edit(.:format)                                                          users/registrations#icon_edit
# users_guest_customer_sign_in POST   /users/guest_customer_sign_in(.:format)                                                  users/sessions#guest_customer
#  users_guest_courier_sign_in POST   /users/guest_courier_sign_in(.:format)                                                   users/sessions#guest_courier
#                         root GET    /                                                                                        contents#index
#                         home GET    /home(.:format)                                                                          contents#home
#                       thanks GET    /thanks(.:format)                                                                        contents#thanks
#               history_orders GET    /orders/history(.:format)                                                                orders#history
#               confirm_orders POST   /orders/confirm(.:format)                                                                orders#confirm
#                       orders GET    /orders(.:format)                                                                        orders#index
#                              POST   /orders(.:format)                                                                        orders#create
#                    new_order GET    /orders/new(.:format)                                                                    orders#new
#                   edit_order GET    /orders/:id/edit(.:format)                                                               orders#edit
#                        order PATCH  /orders/:id(.:format)                                                                    orders#update
#                              PUT    /orders/:id(.:format)                                                                    orders#update
#        conversation_messages GET    /conversations/:conversation_id/messages(.:format)                                       messages#index
#                              POST   /conversations/:conversation_id/messages(.:format)                                       messages#create
#                conversations POST   /conversations(.:format)                                                                 conversations#create
#            letter_opener_web        /letter_opener                                                                           LetterOpenerWeb::Engine
#           rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#    rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#           rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#    update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#         rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
#
# Routes for RailsAdmin::Engine:
#   dashboard GET         /                                  rails_admin/main#dashboard
#       index GET|POST    /:model_name(.:format)             rails_admin/main#index
#         new GET|POST    /:model_name/new(.:format)         rails_admin/main#new
#      export GET|POST    /:model_name/export(.:format)      rails_admin/main#export
# bulk_delete POST|DELETE /:model_name/bulk_delete(.:format) rails_admin/main#bulk_delete
# bulk_action POST        /:model_name/bulk_action(.:format) rails_admin/main#bulk_action
#        show GET         /:model_name/:id(.:format)         rails_admin/main#show
#        edit GET|PUT     /:model_name/:id/edit(.:format)    rails_admin/main#edit
#      delete GET|DELETE  /:model_name/:id/delete(.:format)  rails_admin/main#delete
#
# Routes for LetterOpenerWeb::Engine:
# clear_letters DELETE /clear(.:format)                 letter_opener_web/letters#clear
# delete_letter DELETE /:id(.:format)                   letter_opener_web/letters#destroy
#       letters GET    /                                letter_opener_web/letters#index
#        letter GET    /:id(/:style)(.:format)          letter_opener_web/letters#show
#               GET    /:id/attachments/:file(.:format) letter_opener_web/letters#attachment

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessionts: 'users/sessions',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
    get 'users/user_icon_edit', to: 'users/registrations#icon_edit'
    post 'users/guest_customer_sign_in', to: 'users/sessions#guest_customer'
    post 'users/guest_courier_sign_in', to: 'users/sessions#guest_courier'
  end

  root 'contents#index'
  get '/home', to: 'contents#home'
  get '/thanks', to: 'contents#thanks'
  resources :orders, only: [:index, :new, :create, :edit, :update] do
    collection do
      get :history
      post :confirm
    end
  end

  resources :conversations, only: [:create] do
    resources :messages, only: [:index, :create]
  end

  # if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  # end
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id             :bigint           not null, primary key
#  completed_date :datetime
#  content        :text             not null
#  deadline       :datetime         not null
#  note           :text
#  status         :integer          default("依頼中"), not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  courier_id     :integer
#  customer_id    :integer          not null
#
# Indexes
#
#  index_orders_on_courier_id   (courier_id)
#  index_orders_on_customer_id  (customer_id)
#
# Foreign Keys
#
#  fk_rails_...  (courier_id => users.id)
#  fk_rails_...  (customer_id => users.id)
#
class Order < ApplicationRecord
  has_one :conversation, dependent: :destroy
  belongs_to :user, optional: true
  belongs_to :customer, foreign_key: :customer_id, class_name: 'User', optional: true
  belongs_to :courier, foreign_key: :courier_id, class_name: 'User', optional: true

  enum status: {
    依頼中: 0,
    配達員決定: 1,
    配達完了: 2
  }

  validates :content, presence: true, length: { minimum: 1 }
  validate :check_deadline

  def check_deadline
    if deadline <= DateTime.now
      errors.add(:deadline, 'が現在の日時より前に設定されています')
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:edit, :update]
  before_action :not_authorized_from_courier, only: [:new, :confirm, :create]
  before_action :not_authorized_from_customer, only: [:index, :update]
  before_action :my_items

  def index
    if params[:sort_pass]
      @orders =
      if params[:sort] == 'created_at'
        Order.where(status: 0).order(created_at: :desc)
      elsif params[:sort] == 'deadline'
        Order.where(status: 0).order(deadline: :asc)
      end

      render :index
    end
    @orders = Order.where(status: 0).where('deadline > ?', DateTime.now).order(created_at: :desc)
  end

  def new
    @order = Order.new
  end

  def confirm
    @order = Order.new(order_params)
    @order_content = @order.content.gsub(/\r\n|\r|\n/, '<br>').html_safe
    @order_note = @order.note.gsub(/\r\n|\r|\n/, '<br>').html_safe
    render :new if @order.invalid?
  end

  def create
    @order = Order.new(order_params)
    @order.customer_id = current_user.id
    if params[:back]
      render :new
    else
      if @order.save
        OrderConfirmationMailer.order_confirmation(@order).deliver
        redirect_to home_path, notice: '買い物依頼ありがとうございます！配達員が見つかるのをお待ちください。'
      else
        render :new
      end
    end
  end

  def edit
    @order = Order.find(params[:id])

    @order_content = @order.content.gsub(/\r\n|\r|\n/, '<br>').html_safe
    @order_note = @order.note.gsub(/\r\n|\r|\n/, '<br>').html_safe
    if current_user.category == 'カスタマー'
      if current_user.id != @order.customer_id
        redirect_to home_path
      end
    elsif current_user.category == '配達員'
      if @order.status == '配達員決定' || @order.status == '配達完了'
        if current_user.id != @order.courier_id
          redirect_to home_path
        end
      end
    end
  end

  def update
    @order.courier_id = current_user.id
    if @order.update(order_params)
      if params[:commit] == '依頼受託'
        DelivererDecisionMailer.deliverer_decision(@order).deliver
        flash[:notice] = '依頼を受託しました。買い物に向かいましょう！'
      else
        flash[:notice] = '配達完了を報告しました。お疲れさまでした！'
      end
      redirect_to home_path
    else
      render :edit
    end
  end

  def history
    @orders =
    if current_user.category == 'カスタマー'
      Order.where(customer_id: current_user.id).where(status: 2).order(created_at: :desc)
    elsif current_user.category == '配達員'
      Order.where(courier_id: current_user.id).where(status: 2).order(created_at: :desc)
    end

  end

  private

  def order_params
    params.require(:order).permit(:content, :note, :status, :deadline, :completed_date, :customer_id, :courier_id)
  end

  def set_order
    @order = Order.find(params[:id])
  end

  def my_items
    @customer_orders0 = Order.where(customer_id: current_user.id).where(status: 0)
    @customer_orders1 = Order.where(customer_id: current_user.id).where(status: 1)
    @courier_orders = Order.where(courier_id: current_user.id).where(status: 1)
    @now = DateTime.now
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/confirm.html.erb
<div id="kirehashi"></div>
<%= render 'common/menu_btn' %>

<div id="main_container" class="flex">
  <%= render 'common/side_menu' %>
  <div class="triangle"></div>

  <div id="bg_main" class="order_detail top_space">
    <div class="confirm">
      <p class="form_info">買い物依頼を確定してもよろしいですか？</p>
      <table class="confirm_table">
        <tr>
          <th>買い物リスト</th>
          <td><%= @order_content %></td>
        </tr>
        <tr>
          <th>備考</th>
          <td><%= @order_note %></td>
        </tr>
        <tr>
          <th>終了期限</th>
          <td><%= l @order.deadline, format: :short %></td>
        </tr>
      </table>

      <div class="line_area">
        <%= image_tag 'line.png', class: 'line_image' %>
      </div>

      <div class="new_order_form_address">
        〒<%= current_user.postal_code %><br>
        <%= current_user.address %><br>
        <%= current_user.phone_number %>
        <p><%= current_user.family_name %><%= current_user.first_name %>様</p>
      </div>

      <%= form_with(model: @order, local: true, class: 'confirm_form') do |f| %>
        <%= f.hidden_field :content %>
        <%= f.hidden_field :note %>
        <%= f.hidden_field :deadline %>
        <div class="confirm_btn_area">
          <%= f.submit '戻る', name: 'back', class: 'btn common_btn btn_shadow_dark back_btn' %>
          <%= f.submit '依頼確定', class: 'btn common_btn btn_shadow_dark done_btn' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/edit.html.erb
<div id="kirehashi"></div>
<%= render 'common/menu_btn' %>

<div id="main_container" class="flex">
  <%= render 'common/side_menu' %>
  <div class="triangle"></div>

  <div id="bg_main" class="order_edit top_space">
    <div class="note order_detail_note bottom_space">
      <div class="note_content order_detail_note_content">
        <table class="note_content_table order_detail_note_content_table">
          <tr>
            <th>
              <%= image_tag 'postit1.png', class: 'postit_image' %>
              <p class="postit_content postit_content_shopping_list">買い物リスト</p>
            </th>
            <td><%= @order_content %></td>
          </tr>
          <tr>
            <th>
              <%= image_tag 'postit2.png', class: 'postit_image' %>
              <p class="postit_content postit_content_note">備考</p>
            </th>
            <td><%= @order.note %></td>
          </tr>
          <tr>
            <th>
              <%= image_tag 'postit3.png', class: 'postit_image' %>
              <p class="postit_content postit_content_address">配送先情報</p>
            </th>
            <td>
              〒<%= @order.customer.postal_code %><br>
              <%= @order.customer.address %><br>
              <%= @order.customer.phone_number %>
              <p><%= @order.customer.family_name %>
                <%= @order.customer.first_name %>
                様
              </p>
            </td>
          </tr>
          <tr>
            <th>
              <%= image_tag 'postit4.png', class: 'postit_image' %>
              <p class="postit_content postit_content_status">ステータス</p>
            </th>
            <td><%= @order.status %></td>
          </tr>
          <% if @order.courier.present? %>
            <tr>
              <th>
                <%= image_tag 'postit5.png', class: 'postit_image' %>
                <p class="postit_content postit_content_courier">配達員</p>
              </th>
              <td><%= @order.courier.family_name %></td>
            </tr>
          <% end %>
          <tr>
            <% if @order.status == '依頼中' || @order.status == '配達員決定' %>
              <th>
                <%= image_tag 'postit6.png', class: 'postit_image' %>
                <p class="postit_content postit_content_deadline">終了期限</p>
              </th>
              <td><%= l @order.deadline, format: :short %></td>
            <% elsif @order.status == '配達完了' %>
              <th>
                <%= image_tag 'postit6.png', class: 'postit_image' %>
                <p class="postit_content postit_content_completed_date">配達完了日時</p>
              </th>
              <td><%= l @order.completed_date, format: :short %></td>
            <% end %>
          </tr>
          <tr>
            <th>
              <%= image_tag 'postit7.png', class: 'postit_image' %>
              <p class="postit_content postit_content_created_at">依頼日時</p>
            </th>
            <td><%= l @order.created_at, format: :short %></td>
          </tr>
        </table>

        <% if current_user.category == '配達員' %>
          <% if @order.status == '依頼中' %>
            <div class="note_btn_area">
              <%= form_with(model: @order, local: true) do |f| %>
                <%= f.hidden_field :status, value: '配達員決定' %>
                <span class="memo_submit_btn">
                  <%= f.submit '依頼受託', class: 'btn common_btn memo_btn_shadow' %>
                </span>
              <% end %>
            </div>
          <% elsif @order.status == '配達員決定' %>
            <div class="note_btn_area">
              <%= form_with(model: @order, local: true) do |f| %>
                <%= f.hidden_field :status, value: '配達完了' %>
                <%= f.hidden_field :completed_date, value: DateTime.now %>
                <span class="memo_submit_btn">
                  <%= f.submit '配達完了', class: 'btn common_btn memo_btn_shadow' %>
                </span>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="order_id">注文ID:
        <%= @order.id %></div>
    </div>
  </div>
</div>

app/views/orders/history.html.erb
<div id="kirehashi"></div>
<%= render 'common/menu_btn' %>

<div id="main_container" class="flex">
  <%= render 'common/side_menu' %>
  <div class="triangle"></div>

  <div id="bg_main" class="order_histories top_space">
    <% if @orders.present? %>
      <% @orders.each do |order| %>
        <% order_content = order.content.gsub(/\r\n|\r|\n/, '<br>').html_safe %>
        <div class="order_history">
          <%= image_tag 'memo3.png', class: 'memo_image memo_history_image' %>
          <table class="order_history_list tilt">
            <tr>
              <td class="table_right"><%= order_content[0,9] %>...</td>
              <% if current_user.category == 'カスタマー' %>
                  <td>配達員:<%= order.courier.family_name %></td>
              <% elsif current_user.category == '配達員' %>
                  <td>
                    〒<%= order.customer.postal_code %><br>
                    <%= order.customer.address[0..2] %>...<br>
                    <p class="order_history_name"><%= order.customer.family_name %>
                      <%= order.customer.first_name %>
                      様</p>
                  </td>
              <% end %>
            </tr>
            <tr>
              <th>配達完了日時</th>
              <td><%= l order.completed_date, format: :short %></td>
            </tr>
            <tr>
              <th>依頼日時</th>
              <td><%= l order.created_at, format: :short %></td>
            </tr>
            <tr>
              <td colspan="2" class="table_btn">
                <%= link_to '依頼詳細', edit_order_path(order.id), class: 'btn requesting_btn memo_btn_shadow' %>
              </td>
            </tr>
          </table>
        </div>
      <% end %>
    <% else %>
      <div class="no_history">履歴はまだありません</div>
    <% end %>
  </div>
</div>

app/views/orders/index.html.erb
<div id="kirehashi"></div>
<%= render 'common/menu_btn' %>

<div id="main_container" class="flex">
  <%= render 'common/side_menu' %>
  <div class="triangle"></div>

  <div id="bg_main" class="orders_sort top_space">
    <div class="sort">
      <%= form_with(url: orders_path, method: :get, local: true) do |f| %>
        <%= f.select :sort, options_for_select([['投稿が新しい順','created_at'],['終了期限が早い順','deadline']]),
          { class: 'sort_select' } %>
        <%= f.hidden_field :sort_pass, value: true %>
        <%= f.submit '並べ替え' %>
      <% end %>
    </div>
    <div class="orders">
      <% if @orders.present? %>
        <% @orders.each do |order| %>
          <% order_content = order.content.gsub(/\r\n|\r|\n/, '<br>').html_safe %>
          <% now = DateTime.now %>
          <% deadline = order.deadline.to_datetime %>
          <% if deadline > now %>
            <div class="order">
              <%= image_tag 'memo2.png', class: 'memo_image memo_order_list_image' %>
              <table class="order_table tilt">
                <tr>
                  <td class="table_right"><%= order_content[0,9] %>...</td>
                  <td>
                    〒<%= order.customer.postal_code %><br>
                    <%= order.customer.address[0..2] %>...<br>
                    <p class="order_history_name"><%= order.customer.family_name %>
                      <%= order.customer.first_name %>
                      様</p>
                  </td>
                </tr>
                <tr>
                  <th>終了期限</th>
                  <td><%= l order.deadline, format: :short %></td>
                </tr>
                <tr>
                  <th>依頼日時</th>
                  <td><%= l order.created_at, format: :short %></td>
                </tr>
                <tr>
                  <td colspan="2" class="table_btn">
                    <%= link_to '依頼詳細', edit_order_path(order.id), class: 'btn requesting_btn memo_btn_shadow' %>
                  </td>
                </tr>
              </table>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <div class="sort">現在依頼はありません</div>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<div id="kirehashi"></div>
<%= render 'common/menu_btn' %>

<div id="main_container" class="flex">
  <%= render 'common/side_menu' %>
  <div class="triangle"></div>

  <div id="bg_main" class="new_order top_space">
    <div id="" class="form_container">
      <% if @order.errors.any? %>
        <div class="note error_message_note">
            <div class="note_content error_message_note_content">
              <div id="error_explanation">
                <ul>
                  <% @order.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            </div>
        </div>
      <% end %>
      <%= form_with(model: @order, local: true, url: confirm_orders_path, class: 'form') do |f| %>
        <h4>買い物メモを作りましょう！</h4>
        <div class="form_header">
          <div class="new_order_form_content">
            <%= f.text_area :content %>
          </div>

          <div class="new_order_form_note">
            <div class="new_order_form_note_label">
              <%= f.label :note, class: 'form_info' %>
            </div>
            <%= f.text_area :note, placeholder: '代替品の指定や、別住所への配送の希望などございましたらこちらにご記入ください。' %>
          </div>

          <div class="new_order_form_deadline">
            <%= f.label :deadline, class: 'form_info' %>
            <%= f.datetime_select :deadline,
              use_month_numbers: true,
              start_year: Time.current.year,
              end_year: Time.current.year,
              default: DateTime.now,
              date_separator: '/'
            %>
          </div>
        </div>
          <p class="form_info_condition">終了期限が過ぎた時点で配送員が見つからない場合は自動キャンセルとなります</p>

          <div class="line_area">
            <%= image_tag 'line.png', class: 'line_image' %>
          </div>

          <p class="form_info">お届け先は以下でよろしいですか？</p>
          <div class="new_order_form_address">
            〒<%= current_user.postal_code %><br>
            <%= current_user.address %><br>
            <%= current_user.phone_number %>
            <p><%= current_user.family_name %><%= current_user.first_name %>様</p>
          </div>

          <div class="line_area">
            <%= image_tag 'line.png', class: 'line_image' %>
          </div>

          <div class="new_order_form_submit">
            <%= f.submit '依頼する', class: 'btn common_btn btn_shadow_dark' %>
          </div>
        <% end %>
    </div>
  </div>
</div>