config/routes.rb
# == Route Map
#
#                       Prefix Verb   URI Pattern                                                                              Controller#Action
#                  rails_admin        /admin                                                                                   RailsAdmin::Engine
#             new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#                 user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#         destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#            new_user_password GET    /users/password/new(.:format)                                                            users/passwords#new
#           edit_user_password GET    /users/password/edit(.:format)                                                           users/passwords#edit
#                user_password PATCH  /users/password(.:format)                                                                users/passwords#update
#                              PUT    /users/password(.:format)                                                                users/passwords#update
#                              POST   /users/password(.:format)                                                                users/passwords#create
#     cancel_user_registration GET    /users/cancel(.:format)                                                                  users/registrations#cancel
#        new_user_registration GET    /users/sign_up(.:format)                                                                 users/registrations#new
#       edit_user_registration GET    /users/edit(.:format)                                                                    users/registrations#edit
#            user_registration PATCH  /users(.:format)                                                                         users/registrations#update
#                              PUT    /users(.:format)                                                                         users/registrations#update
#                              DELETE /users(.:format)                                                                         users/registrations#destroy
#                              POST   /users(.:format)                                                                         users/registrations#create
#                      sign_in GET    /sign_in(.:format)                                                                       users/sessions#new
#                     sign_out GET    /sign_out(.:format)                                                                      users/sessions#destroy
#         users_user_icon_edit GET    /users/user_icon_edit(.:format)                                                          users/registrations#icon_edit
# users_guest_customer_sign_in POST   /users/guest_customer_sign_in(.:format)                                                  users/sessions#guest_customer
#  users_guest_courier_sign_in POST   /users/guest_courier_sign_in(.:format)                                                   users/sessions#guest_courier
#                         root GET    /                                                                                        contents#index
#                         home GET    /home(.:format)                                                                          contents#home
#                       thanks GET    /thanks(.:format)                                                                        contents#thanks
#               history_orders GET    /orders/history(.:format)                                                                orders#history
#               confirm_orders POST   /orders/confirm(.:format)                                                                orders#confirm
#                       orders GET    /orders(.:format)                                                                        orders#index
#                              POST   /orders(.:format)                                                                        orders#create
#                    new_order GET    /orders/new(.:format)                                                                    orders#new
#                   edit_order GET    /orders/:id/edit(.:format)                                                               orders#edit
#                        order PATCH  /orders/:id(.:format)                                                                    orders#update
#                              PUT    /orders/:id(.:format)                                                                    orders#update
#        conversation_messages GET    /conversations/:conversation_id/messages(.:format)                                       messages#index
#                              POST   /conversations/:conversation_id/messages(.:format)                                       messages#create
#                conversations POST   /conversations(.:format)                                                                 conversations#create
#            letter_opener_web        /letter_opener                                                                           LetterOpenerWeb::Engine
#           rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#    rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#           rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#    update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#         rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
#
# Routes for RailsAdmin::Engine:
#   dashboard GET         /                                  rails_admin/main#dashboard
#       index GET|POST    /:model_name(.:format)             rails_admin/main#index
#         new GET|POST    /:model_name/new(.:format)         rails_admin/main#new
#      export GET|POST    /:model_name/export(.:format)      rails_admin/main#export
# bulk_delete POST|DELETE /:model_name/bulk_delete(.:format) rails_admin/main#bulk_delete
# bulk_action POST        /:model_name/bulk_action(.:format) rails_admin/main#bulk_action
#        show GET         /:model_name/:id(.:format)         rails_admin/main#show
#        edit GET|PUT     /:model_name/:id/edit(.:format)    rails_admin/main#edit
#      delete GET|DELETE  /:model_name/:id/delete(.:format)  rails_admin/main#delete
#
# Routes for LetterOpenerWeb::Engine:
# clear_letters DELETE /clear(.:format)                 letter_opener_web/letters#clear
# delete_letter DELETE /:id(.:format)                   letter_opener_web/letters#destroy
#       letters GET    /                                letter_opener_web/letters#index
#        letter GET    /:id(/:style)(.:format)          letter_opener_web/letters#show
#               GET    /:id/attachments/:file(.:format) letter_opener_web/letters#attachment

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessionts: 'users/sessions',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
    get 'users/user_icon_edit', to: 'users/registrations#icon_edit'
    post 'users/guest_customer_sign_in', to: 'users/sessions#guest_customer'
    post 'users/guest_courier_sign_in', to: 'users/sessions#guest_courier'
  end

  root 'contents#index'
  get '/home', to: 'contents#home'
  get '/thanks', to: 'contents#thanks'
  resources :orders, only: [:index, :new, :create, :edit, :update] do
    collection do
      get :history
      post :confirm
    end
  end

  resources :conversations, only: [:create] do
    resources :messages, only: [:index, :create]
  end

  # if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  # end
end

app/views/common/_menu_btn.html.erb
<div class="menu_btns">
  <% if current_user.category == 'カスタマー' %>
    <%= link_to '新規買い物依頼', new_order_path, class: 'menu_btn mypage_new_order_btn' %>
    <%= link_to '会員情報編集', edit_user_registration_path, class: 'menu_btn mypage_user_edit_btn' %>
    <%= link_to '買い物履歴', history_orders_path, class: 'menu_btn mypage_shopping_list_btn' %>
  <% elsif current_user.category == '配達員' %>
    <%= link_to '依頼一覧', orders_path, class: 'menu_btn mypage_order_list_btn' %>
    <%= link_to '会員情報編集', edit_user_registration_path, class: 'menu_btn mypage_user_edit_btn' %>
    <%= link_to '配達履歴', history_orders_path, class: 'menu_btn mypage_delivery_list_btn' %>
  <% end %>
</div>

app/views/common/_side_menu.html.erb
<div class="menu_view top_space">
  <div class="sticky_parent">
    <div class="menu">
      <div class="menu_view_user_area">
        <div class="menu_view_user">
          <div class="mypage_user_category">
            <%= current_user.category %>
          </div>
          <div class="mypage_user_name">
            <%= link_to home_path do %>
              <%= current_user.family_name %>
              <%= current_user.first_name %>
              様
            <% end %>
          </div>
        </div>
        <div class="mypage_user_icon">
          <% if current_user.icon.present? %>
            <%= image_tag current_user.icon.url, class: 'user_icon_image mypage_user_icon_common mypage_user_icon_image' %>
          <% else %>
            <%= icon 'fas', 'user-circle', class: 'user_icon mypage_user_icon_common mypage_user_icon' %>
          <% end %>
        </div>
      </div>
      <div class= flash_area>
        <% flash.each do |message_type, message| %>
          <div id="flash" class="home_flash">
            <h1><%= message %></h1>
          </div>
        <% end %>
      </div>
    </div>

    <% unless action_name == 'home' %>
      <div class="menu_requestings">
        <% if current_user.category == 'カスタマー' %>
          <% if @customer_orders0.present? %>
            <% @customer_orders0.each do |order| %>
              <% deadline = order.deadline.to_datetime %>
              <% if deadline > @now %>
                <div class="menu_requesting">
                  <div class="menu_requesting_content">
                    <p class="menu_requesting_info">依頼中の買い物</p>
                    <div class="menu_requesting_text">
                      現在配達員を探しています。<br>
                      依頼期限：<%= l order.deadline, format: :short %>
                    </div>
                    <%= link_to '依頼詳細', edit_order_path(order.id), class: 'btn requesting_btn menu_requesting_btn btn_shadow' %>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
          <% if @customer_orders1.present? %>
            <% @customer_orders1.each do |order| %>
              <% deadline = order.deadline.to_datetime %>
              <% if deadline > @now %>
                <div class="menu_requesting">
                  <div class="menu_requesting_content">
                    <p class="menu_requesting_info">依頼中の買い物</p>
                    <div class="menu_requesting_text">
                      配達員が決まりました！<br>
                      <%= order.courier.family_name %>が買い物・配達に伺います。
                    </div>
                    <%= link_to '依頼詳細', edit_order_path(order.id), class: 'btn requesting_btn menu_requesting_btn btn_shadow' %>
                    <%= link_to '配達員に連絡', conversations_path(sender_id: current_user.id, recipient_id: order.courier_id, order_id: order.id), method: :post, class: 'btn requesting_btn requesting_message_btn menu_requesting_btn memo_btn_shadow' %>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
        <% elsif current_user.category == '配達員' %>
          <% if @courier_orders.present? %>
            <% @courier_orders.each do |order| %>
              <% deadline = order.deadline.to_datetime %>
              <% if deadline > @now %>
                <div class="menu_requesting">
                  <div class="menu_requesting_content">
                    <p class="menu_requesting_info">受託中の依頼</p>
                    <div class="menu_requesting_text">
                      <%= order.customer.family_name %>
                      <%= order.customer.first_name %>
                      様の買い物依頼<br>
                      依頼期限：<%= l order.deadline, format: :short %>
                    </div>
                    <%= link_to '依頼詳細', edit_order_path(order.id), class: 'btn requesting_btn menu_requesting_btn btn_shadow' %>
                    <%= link_to 'カスタマーに連絡', conversations_path(sender_id: current_user.id, recipient_id: order.customer_id, order_id: order.id), method: :post, class: 'btn requesting_btn requesting_message_btn menu_requesting_btn memo_btn_shadow' %>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>